// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:802b912b-f266-49fc-b04b-50816981bc73",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_WCHjR9OQY",
    "aws_user_pools_web_client_id": "1igj55o1vij92rmnh1s42853kn"
};


export default awsmobile;
